void azure_auth_header_module_init(void);
void pseudofile_module_init(void);
void afsql_module_init(void);
void disk_buffer_module_init(void);
void add_contextual_data_module_init(void);
void appmodel_module_init(void);
void kvformat_module_init(void);
void riemann_module_init(void);
void linux_kmsg_format_module_init(void);
void hook_commands_module_init(void);
void afuser_module_init(void);
void xml_module_init(void);
void cloud_auth_module_init(void);
void systemd_journal_module_init(void);
void afamqp_module_init(void);
void confgen_module_init(void);
void correlation_module_init(void);
void http_module_init(void);
void rate_limit_filter_module_init(void);
void python_module_init(void);
void map_value_pairs_module_init(void);
void afsnmp_module_init(void);
void clickhouse_module_init(void);
void bigquery_module_init(void);
void google_pubsub_grpc_module_init(void);
void loki_module_init(void);
void grpc_filterx_module_init(void);
void otel_module_init(void);
void csvparser_module_init(void);
void graphite_module_init(void);
void json_plugin_module_init(void);
void timestamp_module_init(void);
void syslogformat_module_init(void);
void cef_module_init(void);
void afprog_module_init(void);
void metrics_probe_module_init(void);
void afsocket_module_init(void);
void kafka_module_init(void);
void regexp_parser_module_init(void);
void stardate_module_init(void);
void affile_module_init(void);
void tags_parser_module_init(void);

void
modules_ref(void)
{
  azure_auth_header_module_init();
  pseudofile_module_init();
  afsql_module_init();
  disk_buffer_module_init();
  add_contextual_data_module_init();
  appmodel_module_init();
  kvformat_module_init();
  riemann_module_init();
  linux_kmsg_format_module_init();
  hook_commands_module_init();
  afuser_module_init();
  xml_module_init();
  cloud_auth_module_init();
  systemd_journal_module_init();
  afamqp_module_init();
  confgen_module_init();
  correlation_module_init();
  http_module_init();
  rate_limit_filter_module_init();
  python_module_init();
  map_value_pairs_module_init();
  afsnmp_module_init();
  clickhouse_module_init();
  bigquery_module_init();
  google_pubsub_grpc_module_init();
  loki_module_init();
  grpc_filterx_module_init();
  otel_module_init();
  csvparser_module_init();
  graphite_module_init();
  json_plugin_module_init();
  timestamp_module_init();
  syslogformat_module_init();
  cef_module_init();
  afprog_module_init();
  metrics_probe_module_init();
  afsocket_module_init();
  kafka_module_init();
  regexp_parser_module_init();
  stardate_module_init();
  affile_module_init();
  tags_parser_module_init();
}
