#!/bin/bash

# arguments
prof="${1:-}"
config="${2:-/dbld/callgrind-syslog-ng.conf}"
samples="${3:-/dbld/callgrind-samples.log}"
dbld_root="${4:-/}"

# variables
mkdir -p /build/callgrind
if [ "$prof" = "" ]; then
	outdir=`mktemp -d -p /build/callgrind report-$(date +%H%M%S).XXXX`
else
	outdir="/build/callgrind/$prof"
	mkdir -p "${outdir}"
fi


(cd /source && git log -1) >> "$outdir/git-commit"

export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so

# Cache layout is coming from: Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
#
# LEVEL1_ICACHE_SIZE                 32768
# LEVEL1_ICACHE_ASSOC
# LEVEL1_ICACHE_LINESIZE             64
# LEVEL1_DCACHE_SIZE                 32768
# LEVEL1_DCACHE_ASSOC                8
# LEVEL1_DCACHE_LINESIZE             64
# LEVEL2_CACHE_SIZE                  1048576
# LEVEL2_CACHE_ASSOC                 16
# LEVEL2_CACHE_LINESIZE              64
# LEVEL3_CACHE_SIZE                  37486592
# LEVEL3_CACHE_ASSOC                 11
# LEVEL3_CACHE_LINESIZE              64
# LEVEL4_CACHE_SIZE
# LEVEL4_CACHE_ASSOC
# LEVEL4_CACHE_LINESIZE
#
# we are using L3 as the LL to model miss-to-memory style issues.
# with L2 as LL, we could simulate core-local behaviour.
#
# Unfortunately the L3 cache size is not a power of two (probably because
# the number of cores is not either), so I've rounded it to 32MB.
#
# we could be using L2 as the LL: --LL=1048576,16,64
valgrind --tool=callgrind --dump-instr=yes --collect-jumps=yes \
	--I1=32768,8,64 --D1=32768,8,64 --LL=33554432,8,64  --cache-sim=yes \
	--instr-atstart=no \
	--callgrind-out-file="${outdir}/callgrind.out.%p"  \
	/install/sbin/syslog-ng -Fef "$config" 2>"$outdir/summary.txt" &
# wait until syslog-ng starts up
i=0
while ! grep -q "Accepting connections" "$outdir/summary.txt"; do
	sleep 0.5
	i=$[i+1]
	if [ $i -gt 20 ]; then
		echo "Timeout waiting for startup, waiting for process to exit"
		wait %1
		cat "$outdir/summary.txt"
		exit 1
	fi
done
cat "$samples" | nc -q0 localhost 2000
kill -INT %1
wait %1
cat "$outdir/summary.txt"
callgrind_annotate --tree=both --threshold=80 ${outdir}/callgrind.out.* > "${outdir}/callgrind_annotate.txt"
echo -en "\n\nTo see profile details do:\nless "
echo "${outdir}/callgrind_annotate.txt" | sed -e "s,^/,$dbld_root/,"
