{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "axosyslog.fullname" . }}
  namespace: {{ include "axosyslog.namespace" . }}
  labels:
    {{- include "axosyslog.collector.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.podMonitor.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.podMonitor.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "axosyslog.collector.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: exporter
{{- end }}
