{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "axosyslog.fullname" . }}-aggregator
  namespace: {{ include "axosyslog.namespace" . }}
  labels:
    {{- include "axosyslog.aggregator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    {{- include "axosyslog.aggregator.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
{{ if .Values.service.extraPorts }}
{{ toYaml ( .Values.service.extraPorts ) | nindent 4 }}
{{ end }}

{{- with .Values.syslog.config.sources }}
{{- if .syslog.enabled }}
    - name: rfc3164-udp
      protocol: UDP
      {{- if and .syslog.rfc3164UdpPort (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) }}
      nodePort: {{ .syslog.rfc3164UdpPort }}
      {{- end }}
      port: 514
      targetPort: rfc3164-udp
    - name: rfc3164-tcp
      protocol: TCP
      {{- if and .syslog.rfc3164TcpPort (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) }}
      nodePort: {{ .syslog.rfc3164TcpPort }}
      {{- end }}
      port: 514
      targetPort: rfc3164-tcp
    - name: rfc5424-tls
      protocol: TCP
      {{- if and .syslog.rfc5424TlsPort (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) }}
      nodePort: {{ .syslog.rfc5424TlsPort }}
      {{- end }}
      port: 6514
      targetPort: rfc5424-tls
    - name: rfc5424-tcp
      protocol: TCP
      {{- if and .syslog.rfc5424TcpPort (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) }}
      nodePort: {{ .syslog.rfc5424TcpPort }}
      {{- end }}
      port: 601
      targetPort: rfc5424-tcp
{{- end }}
{{- if .axosyslogOtlp.enabled }}
    - name: otlp
      protocol: TCP
      {{- if and .axosyslogOtlp.port (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) }}
      nodePort: {{ .axosyslogOtlp.port }}
      {{- end }}
      port: 4317
      targetPort: otlp
{{- end }}
{{- end }}
{{- end }}