{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "axosyslog.fullname" . }}-syslog
spec:
  selector:
    app: {{ template "axosyslog.fullname" . }}-syslog
  type: {{ .Values.service.type | default "NodePort" }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
{{ if .Values.service.extraPorts }}
{{ toYaml ( .Values.service.extraPorts ) | nindent 4 }}
{{ end }}

{{- with .Values.syslog.config.sources }}
{{- if .syslog.enabled }}
    - name: rfc3164-udp
      protocol: UDP
      {{- if .syslog.rfc3164UdpPort }}
      nodePort: {{ .syslog.rfc3164UdpPort }}
      {{- end }}
      port: 514
      targetPort: rfc3164-udp
    - name: rfc3164-tcp
      protocol: TCP
      {{- if .syslog.rfc3164TcpPort }}
      nodePort: {{ .syslog.rfc3164TcpPort }}
      {{- end }}
      port: 514
      targetPort: rfc3164-tcp
    - name: rfc5424-tls
      protocol: TCP
      {{- if .syslog.rfc5424TlsPort }}
      nodePort: {{ .syslog.rfc5424TlsPort }}
      {{- end }}
      port: 6514
      targetPort: rfc5424-tls
    - name: rfc5424-tcp
      protocol: TCP
      {{- if .syslog.rfc5424TcpPort }}
      nodePort: {{ .syslog.rfc5424TcpPort }}
      {{- end }}
      port: 601
      targetPort: rfc5424-tcp
{{- end }}
{{- if .axosyslogOtlp.enabled }}
    - name: otlp
      protocol: TCP
      {{- if .axosyslogOtlp.port }}
      nodePort: {{ .axosyslogOtlp.port }}
      {{- end }}
      port: 4317
      targetPort: otlp
{{- end }}
{{- end }}
{{- end }}
