name: AxoSyslog charts linter

on:
  push:
    paths:
      - 'charts/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: charts/axosyslog

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Linter
        run: |
          docker run -v${PWD}:${PWD} alpine/helm lint ${PWD}

  helm-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install helm-docs
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install helm-docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest

      - name: Generate docs
        run: scripts/helm-docs.sh

      - name: Check README is up to date
        run: git diff --exit-code charts/axosyslog/README.md
