name: AxoSyslog Docker image builder

permissions: write-all

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string  # stable / snapshot
      platforms:
        required: false
        type: string
        default: linux/amd64,linux/arm64,linux/arm/v7
      snapshot-tarball-artifact:
        required: false
        type: string
      snapshot-version:
        required: false
        type: string
      snapshot-tags: # comma-separated
        required: false
        type: string

env:
  DEBUG_PLATFORM: linux/amd64

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      platform-matrix: ${{ steps.platforms.outputs.platform-matrix }}
      image-name: ${{ steps.registry.outputs.image-name }}
    steps:
      - id: platforms
        name: platform
        env:
          PLATFORMS: ${{ inputs.platforms }}
        run: |
          PLATFORM_MATRIX="$(echo "$PLATFORMS" | jq 'split(",")' -Rc)"
          echo "platform-matrix=$PLATFORM_MATRIX" >> $GITHUB_OUTPUT
      - id: registry
        name: registry
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/axosyslog"
          IMAGE_NAME="$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')"
          echo "image-name=$IMAGE_NAME" >> $GITHUB_OUTPUT

  merge-and-push:
    runs-on: ubuntu-latest
    needs: [prepare]
    outputs:
      tags: ${{ steps.docker-metadata-tags.outputs.tags }}
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: docker-metadata-tags
        name: Extract metadata (AxoSyslog version) for Docker
        run: |
          last_full_version=$(skopeo inspect docker://ghcr.io/axoflow/axosyslog:latest | jq '.RepoTags' | sed 's/ \|"\|,//g' | grep "^[0-9]*.[0-9]*.[0-9]*$\|^[0-9]*.[0-9]*.[0-9]*-[0-9]*$" | tail -n 1)
          if [[ $last_full_version == *"-"* ]]; then
              last_version=$(echo $last_full_version | cut -d"-" -f1)
              last_patch_level=$(echo $last_full_version | cut -d"-" -f2)
              next_patch_level=$((last_patch_level + 1))
          else
              last_version=$(echo $last_full_version | cut -d"-" -f1)
              next_patch_level=1
          fi
          next_full_version="$last_version-$next_patch_level"
          TAGS="ghcr.io/axoflow/axosyslog:$last_version,ghcr.io/axoflow/axosyslog:$next_full_version,ghcr.io/axoflow/axosyslog:latest"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Compose Docker image tags
        id: tags
        env:
          TYPE: ${{ inputs.type }}
          SNAPSHOT_TAGS: ${{ inputs.snapshot-tags }}
          IMAGE_NAME: ${{ needs.prepare.outputs.image-name }}
        run: |
          if [[ "$TYPE" = "stable" ]]; then
            TAGS='${{ steps.docker-metadata-tags.outputs.tags }}'
          elif [[ "$TYPE" = "snapshot" ]]; then
            TAGS="$(echo "$SNAPSHOT_TAGS" | sed "s|[^,]*|$IMAGE_NAME:&|g")"
          else
            echo "Unexpected input: type=$TYPE"
            false
          fi

          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT
          echo "DEBUG_TAGS=${TAGS//,/-dbg,}-dbg" >> $GITHUB_OUTPUT

