name: Check config grammar changes (PR)

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-cfg-grammar-changes:
    name: Check config grammar changes
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: axoflow/axosyslog-cfg-diff-pr@5aad2fdd7552b7164458732cb961ab45c4bbffa8
        continue-on-error: true
