name: Compile dbld-images

permissions: write-all

on:
  pull_request:
    paths:
      - 'dbld/**'
      - 'packaging/rhel/**'
      - 'packaging/debian/**'
      - '.github/workflows/dbld-images.yml'
  push:
    paths:
      - 'dbld/**'
      - 'packaging/rhel/**'
      - 'packaging/debian/**'
      - '.github/workflows/dbld-images.yml'
  schedule:
    - cron: '00 22 * * *'
  workflow_dispatch:
    inputs:
      testing_image_upload:
        description: Should we upload the images into GitHub Packages? (true/false)
        required: false
        default: "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - almalinux-9
          - almalinux-8
          - fedora-41
          - fedora-42
          - debian-bullseye
          - debian-bookworm
          - debian-sid
          - debian-testing
          - debian-trixie
          - ubuntu-focal
          - ubuntu-jammy
          - ubuntu-noble
          - ubuntu-plucky
          - devshell
          - tarball
      fail-fast: false
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set container registry
        run: |
          CONTAINER_REGISTRY="ghcr.io/${{ github.repository_owner }}"
          CONTAINER_REGISTRY="$(echo "$CONTAINER_REGISTRY" | tr '[:upper:]' '[:lower:]')"

          . .github/workflows/gh-tools.sh
          gh_export CONTAINER_REGISTRY

      - name: Build the images
        run: dbld/rules image-${{ matrix.image }}

      - name: Should we upload the images?
        run: |
          if [ "${{ github.event.inputs.testing_image_upload }}" = "true" ] || \
             ( \
              [ "${{ github.repository_owner }}" = "axoflow" ] && \
              [ "${{ github.ref }}" = "refs/heads/main" ] && \
              [[ "${{ github.event_name }}" =~ ^(push|workflow_dispatch|schedule)$ ]] \
            )
          then
            UPLOAD_IMAGES_INTERNAL="true"
          else
            UPLOAD_IMAGES_INTERNAL="false"
          fi

          . .github/workflows/gh-tools.sh
          gh_export UPLOAD_IMAGES_INTERNAL

      - name: Log in to the Container registry
        if: env.UPLOAD_IMAGES_INTERNAL == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the images
        if: env.UPLOAD_IMAGES_INTERNAL == 'true'
        run: |
          dbld/rules push-image-${{ matrix.image }}
