#!/bin/sh -e

orig_version=$(apt-cache policy axosyslog | grep "500$" | awk '{print $1}')

apt_line=""
for pkg in axosyslog \
                axosyslog-core \
                axosyslog-mod-mongodb \
                axosyslog-mod-sql \
                axosyslog-mod-smtp \
                axosyslog-mod-amqp \
                axosyslog-mod-geoip2 \
                axosyslog-mod-redis \
                axosyslog-mod-stomp \
                axosyslog-mod-riemann \
                axosyslog-mod-graphite \
                axosyslog-mod-python \
                axosyslog-mod-add-contextual-data
do
    apt_line="$apt_line $pkg=$orig_version"
done

apt-get install -y --allow-downgrades $apt_line 2>/dev/null
apt-get -u -y dist-upgrade
